import { address } from "@solana/kit";

// addresses
const PROGRAM_ID = address("4ZegtDo8WG6e2PAswLhnGXYDS5TGkniVCKXDrDX12KYX");
const WSOL_MINT = address("So11111111111111111111111111111111111111112");
const USDC_MINT = address("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v");

// seeds
const CONFIG_SEED = Buffer.from("config");
const TREASURY_SEED = Buffer.from("treasury");
const MARKET_SEED = Buffer.from("market");
const FARMER_POSITION_SEED = Buffer.from("farmer_position");

// instruction discriminators
const INITIALIZE_DISCRIMINATOR = 0;
const CREATE_MARKET_DISCRIMINATOR = 1;
const ADD_INCENTIVES_DISCRIMINATOR = 2;
const CANCEL_MARKET_DISCRIMINATOR = 3;
const CLAIM_FEES_DISCRIMINATOR = 4;
const SETTLE_MARKET_DISCRIMINATOR = 5;
const WITHDRAW_TREASURY_DISCRIMINATOR = 6;
const STAKE_OUTCOME_TOKEN_DISCRIMINATOR = 7;

export const constants = {
  PROGRAM_ID,
  WSOL_MINT,
  USDC_MINT,
  CONFIG_SEED,
  TREASURY_SEED,
  MARKET_SEED,
  FARMER_POSITION_SEED,
  INITIALIZE_DISCRIMINATOR,
  CREATE_MARKET_DISCRIMINATOR,
  ADD_INCENTIVES_DISCRIMINATOR,
  CANCEL_MARKET_DISCRIMINATOR,
  CLAIM_FEES_DISCRIMINATOR,
  SETTLE_MARKET_DISCRIMINATOR,
  WITHDRAW_TREASURY_DISCRIMINATOR,
  STAKE_OUTCOME_TOKEN_DISCRIMINATOR,
};
